discord:
  playing-message: "ê³µë¶€ ì•ˆí•˜ëŠ” ì‚¬ëŒë“¤ì„ ê°ì‹œ"
  token: # discord token #
  category-id: # category ID #
  notify-message: "ì–´ì œì˜ ì•ˆì¼í•œ ìƒëª…ì²´ë“¤ì„ ì†Œê°œí•©ë‹ˆë‹¤... ğŸ”ªğŸ©¸\n%s"
github:
  token: # github token #
logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: debug
    org.springframework.web.HttpLogging: debug
